@"
name: CI — Web

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'vite.config.*'
      - 'tsconfig*.json'
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - 'vite.config.*'
      - 'tsconfig*.json'
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - '.github/workflows/web.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix['node-version'] }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present
"@ | Set-Content -Encoding UTF8 ".github/workflows/web.yml"
