name: CI — Web

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'vite.config.*'
      - 'tsconfig*.json'
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - 'vite.config.*'
      - 'tsconfig*.json'
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - '.github/workflows/web.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: 'npm'

      - name: Enable corepack (pnpm/yarn support)
        run: corepack enable

      - name: Install deps (auto-detect package manager)
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          elif [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Typecheck
        run: npm run typecheck --if-present || true

      - name: Lint
        run: npm run lint --if-present || true

      - name: Build
        run: npm run build --if-present || true
